### ISSUE TITLE
Class "IP2LocationLaravel" not found

### ISSUE THREAD

**Issue by PNP-MA** [ip2location/ip2location-laravel#7] opened 2024-01-07 20:48 UTC
A class import is missing
You have a missing class import. Try importing this class: Ip2location\IP2LocationLaravel\Facade\IP2LocationLaravel.

**Comment by ip2location-com** [comment] 2024-01-17 07:49
Hi G6KG,

We are unable to reproduce this error message in Laravel 8, 9 and 10 with the v1.3.1 of IP2Location Laravel. In order to investigate further on the issue, can you please:

1. Provide us the version of the Laravel and IP2Location Laravel that you are using? You can obtain the information by looking at the  _composer.json_ in your Laravel application.
2. Check if the GMP extension in your PHP is enabled? If no, please kindly enable it, update your _composer.json_ in your Laravel application to install the latest version of IP2Location Laravel by changing the `"ip2location/ip2location-laravel": "^1.2",` to `"ip2location/ip2location-laravel": "^1.3",`. After that, run the `composer update` to update the library. This is to make sure that you are installing the latest version of IP2Location Laravel.
3. Provide us the code that you have used to produce the error?

**Comment by ip2location-com** [comment] 2024-02-04 23:42
Hi G6KG,

Since our last communication, we haven't received any additional updates or responses regarding this matter. We understand that circumstances may have changed, or the issue may have been resolved on your end.

After waiting for a reasonable period without further information, we are closing this issue. However, if you still need assistance or have additional details to provide, please feel free to reopen this issue, and we'll be more than happy to continue investigating and addressing your concerns.

Thank you for your initial report and your understanding. If there's anything else we can assist you with, please don't hesitate to reach out.

**Closed as completed by ip2location-com** 2024-02-04 23:42 UTC
